/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/extensions/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User
         * @description Return the email associated with the current token.
         *
         *     The extension can call this on popup open to verify the token is still
         *     valid and to display the current user's email.
         *
         *     Args:
         *         identity: Validated extension identity (injected).
         *
         *     Returns:
         *         MeResponse containing only the user's email.
         *
         *     Raises:
         *         HTTPException: 401 if the token is missing, expired, or user not found.
         */
        get: operations["get_current_user_extensions_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extensions/domain-classification/{domain}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Domain Classification
         * @description Get a domain's classification for extension clients.
         *
         *     Accepts a bare domain or a full URL; the registered domain is extracted
         *     before the lookup. Uses the classification cache to check freshness.
         *
         *     If the domain has no fresh classification, a background classification
         *     job is triggered (fire-and-forget) and a 404 is returned so the client
         *     can retry later.
         *
         *     Args:
         *         domain: Domain name or URL (e.g., "example.com" or "https://example.com").
         *         identity: Validated extension identity (install ID, extension ID, version).
         *
         *     Returns:
         *         DomainClassificationResponse for the requested domain.
         *
         *     Raises:
         *         HTTPException: 400 if the domain/URL is invalid, 404 if not yet classified.
         */
        get: operations["get_domain_classification_extensions_domain_classification__domain__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extensions/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Report
         * @description Submit a threat report for a URL.
         *
         *     The report is stored as a discuss post (PostType.REPORT) and is
         *     queued for LLM-based moderation. The extension's install_id is
         *     used as the fingerprint for audit trail and rate limiting.
         *
         *     Args:
         *         request: Report payload with URL and user explanation.
         *         background_tasks: FastAPI background tasks runner.
         *         identity: Validated extension identity (injected).
         *
         *     Returns:
         *         ExtensionReportResponse with post ID, domain, and status.
         *
         *     Raises:
         *         HTTPException: 400 if the URL is invalid.
         */
        post: operations["submit_report_extensions_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extensions/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initiate Scan
         * @description Submit a new scan request.
         *
         *     Requires authentication and an active subscription.  The user's daily
         *     scan limit (from their subscription) is enforced via a Redis counter.
         *
         *     Args:
         *         request: Scan payload containing URL, screenshot, and HTML.
         *         background_tasks: FastAPI background tasks runner.
         *         identity: Validated extension identity (injected).
         *
         *     Returns:
         *         ScanInitResponse with job ID and polling URL.
         *
         *     Raises:
         *         HTTPException: 401 if not authenticated, 403 if no subscription,
         *             400 if URL is invalid, 429 if daily scan limit exceeded.
         */
        post: operations["initiate_scan_extensions_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extensions/scan/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scan Status
         * @description Poll the status of a scan job.
         *
         *     Only the user who initiated the scan can view its status.
         *
         *     Args:
         *         job_id: The subscription job ID to query.
         *         identity: Validated extension identity (injected).
         *
         *     Returns:
         *         SubscriptionJobStatusResponse with current status, result, or error.
         *
         *     Raises:
         *         HTTPException: 401 if not authenticated, 400 if invalid job ID,
         *             404 if job not found.
         */
        get: operations["get_scan_status_extensions_scan__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extensions/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Subscription
         * @description Return the current user's subscription details.
         *
         *     If the user's email is not yet verified, no subscription is active and
         *     ``is_active`` will be ``False`` with ``None`` limit fields.
         *
         *     Args:
         *         identity: Validated extension identity (injected).
         *
         *     Returns:
         *         SubscriptionResponse with tier name, daily scan limit, and active flag.
         *
         *     Raises:
         *         HTTPException: 401 if the token is missing, expired, or user not found.
         */
        get: operations["get_subscription_extensions_subscription_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * MeResponse
         * @description Response for GET /extensions/auth/me.
         */
        MeResponse: {
            /** Email */
            email: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * DomainClassificationResponse
         * @description Domain classification result for API responses.
         *
         *     Extends base model with custom serialization for API responses.
         */
        DomainClassificationResponse: {
            /**
             * Domain
             * @description The root domain (eTLD+1) that was classified.
             */
            domain: string;
            /** @description Technical metadata from WHOIS, Tranco, and ASN lookups. */
            facts?: components["schemas"]["TechnicalFacts"] | null;
            /** @description Descriptive identity information (LLM-generated). */
            identity?: components["schemas"]["DomainIdentity"] | null;
            /** @description Purpose-based domain classification (LLM-generated). */
            category?: components["schemas"]["DomainCategory"] | null;
            /** @description Structural platform capabilities (LLM-generated). */
            functions?: components["schemas"]["InherentFunctionality"] | null;
            /**
             * @description LLM's confidence in its classification (high, medium, unknown).
             * @default unknown
             */
            confidence: components["schemas"]["ConfidenceLevel"];
            /**
             * Verified
             * @description Whether this classification has been manually verified.
             * @default false
             */
            verified: boolean;
            /**
             * Urlert Notes
             * @description Deprecated — use admin_note. Legacy markdown notes from admins.
             */
            urlert_notes?: string | null;
            /** @description Structured admin note with severity level. Publicly visible. */
            admin_note?: components["schemas"]["AdminNote"] | null;
            /**
             * Created At
             * Format: date-time
             * @description Timestamp when classification was created.
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             * @description Timestamp when classification was last updated.
             */
            updated_at?: string;
        };
        /**
         * TechnicalFacts
         * @description Objective data points fetched during triage (Python-side), NOT from LLM.
         *
         *     These are critical for trust and filtering decisions.
         */
        TechnicalFacts: {
            /**
             * Registered Date
             * @description Domain registration date (from WHOIS/RDAP).
             */
            registered_date?: string | null;
            /**
             * Rank
             * @description Traffic rank from Tranco List. Lower is better (1 = highest traffic). Unranked domains have a value of 999999999999.
             * @default 999999999999
             */
            rank: number | null;
            /**
             * Hosting Provider
             * @description The Infrastructure Provider from the ASN record (e.g., 'Amazon.com', 'GoDaddy'). Note: This identifies the server host, NOT necessarily the business owner.
             */
            hosting_provider?: string | null;
            /**
             * Ip Addresses
             * @description List of resolved IP addresses (IPv4 and IPv6) from DNS lookup.
             */
            ip_addresses?: string[] | null;
        };
        /**
         * DomainIdentity
         * @description Descriptive text about the domain's entity and purpose.
         *
         *     Contains the "who" and "what" of the domain in human-readable form.
         */
        DomainIdentity: {
            /**
             * Headline
             * @description A short, news-ticker style summary.
             */
            headline: string;
            /**
             * Summary
             * @description 2-3 objective sentences describing the organization.
             */
            summary: string;
            /**
             * Operator
             * @description The common name of the entity running the site (e.g., 'GitHub'). Null for infrastructure domains without clear operator.
             */
            operator?: string | null;
            /**
             * Parent Entity
             * @description The parent holding company if known (e.g., 'Microsoft Corporation').
             */
            parent_entity?: string | null;
            /**
             * Topics
             * @description 5-10 SEO-style keywords.
             */
            topics?: string[];
        };
        /**
         * DomainCategory
         * @description Purpose-based domain classification.
         *
         *     Attributes:
         *         purpose: Primary functional purpose (replaces IAB Tier 1).
         *         specialization: Free-text specific niche (2-4 words, replaces IAB Tier 2).
         */
        DomainCategory: {
            /** @description Primary functional purpose of the domain. */
            purpose: components["schemas"]["DomainPurpose"];
            /**
             * Specialization
             * @description Specific niche or focus area (2-4 words). E.g., 'Retail Banking', 'Tech News', 'Version Control'.
             */
            specialization?: string | null;
        };
        /**
         * DomainPurpose
         * @description Primary purpose of a domain - what it fundamentally does.
         *
         *     This replaces IAB Tier 1 with functional categories designed for:
         *     - Clear LLM classification (no ambiguous abstract categories)
         *     - Security risk assessment (maps to InherentFunctionality)
         *     - Modern web platforms (includes URL shorteners, crypto, etc.)
         * @enum {string}
         */
        DomainPurpose: "news_media" | "social_network" | "messaging" | "content_publishing" | "video_streaming" | "audio_streaming" | "ecommerce" | "marketplace" | "financial_services" | "crypto_exchange" | "developer_platform" | "cloud_infrastructure" | "file_storage" | "search_engine" | "url_shortener" | "productivity_suite" | "document_collaboration" | "form_builder" | "email_service" | "identity_provider" | "vpn_proxy" | "knowledge_base" | "educational" | "government" | "gaming" | "adult_content" | "gambling" | "corporate_website" | "blog" | "portfolio" | "dns_infrastructure" | "cdn_edge" | "registrar_parking" | "potentially_malicious";
        /**
         * InherentFunctionality
         * @description Structural features that indicate risk potential.
         *
         *     These are STABLE traits that define what the platform fundamentally does.
         *     Used for URL risk assessment - platforms that can host arbitrary content
         *     or mask destinations are higher risk vectors.
         */
        InherentFunctionality: {
            /**
             * Is Ugc Platform
             * @description Is the CORE purpose to host user-generated content? (e.g., YouTube, GitHub, Reddit)
             * @default false
             */
            is_ugc_platform: boolean;
            /**
             * Is File Host
             * @description Is this a file storage/sharing service? (e.g., Dropbox, WeTransfer)
             * @default false
             */
            is_file_host: boolean;
            /**
             * Is Url Shortener
             * @description Is this a link shortening service? (e.g., bit.ly, t.co)
             * @default false
             */
            is_url_shortener: boolean;
            /**
             * Is Public Idp
             * @description Is this a PUBLIC Identity Provider (IdP) that allows UNAFFILIATED third-party websites to authenticate users? (e.g. 'Sign in with Google', 'Okta', 'Auth0', 'Microsoft Entra'). EXCLUDE internal organizational SSOs (universities, corporate intranets) that only authenticate their own members.
             * @default false
             */
            is_public_idp: boolean;
            /**
             * Is Crypto Platform
             * @description Is this a cryptocurrency exchange, wallet, or dApp? (e.g., Coinbase, Binance)
             * @default false
             */
            is_crypto_platform: boolean;
            /**
             * Allows User Subdomains
             * @description Can anonymous users register their own public subdomain to host content? (e.g., user.github.io, myblog.wordpress.com). Exclude infrastructure domains where subdomains are operator-managed (e.g., ns-1.awsdns-18.com, a1234.akamai.net).
             * @default false
             */
            allows_user_subdomains: boolean;
            /**
             * Is Form Builder
             * @description Is this a form/survey creation platform? (e.g., Google Forms, Typeform, JotForm)
             * @default false
             */
            is_form_builder: boolean;
            /**
             * Is Document Host
             * @description Is this a document/page hosting platform? (e.g., Google Docs, Notion, Coda)
             * @default false
             */
            is_document_host: boolean;
        };
        /**
         * ConfidenceLevel
         * @description Confidence in the classification
         * @enum {string}
         */
        ConfidenceLevel: "high" | "medium" | "unknown";
        /**
         * AdminNote
         * @description Structured admin note with severity level.
         *
         *     Replaces the flat ``urlert_notes`` string so that downstream behaviour
         *     (OTX triggers, scan-score boosts, LLM prompt framing) can be gated on
         *     the severity ``level``.
         *
         *     Attributes:
         *         level: Severity — INFO, WARNING, or DANGER.
         *         content: Markdown note body.
         *         created_at: When the note was written.
         */
        AdminNote: {
            /** @description Severity of the admin note. */
            level: components["schemas"]["AdminNoteLevel"];
            /**
             * Content
             * @description Markdown note body.
             */
            content: string;
            /**
             * Created At
             * Format: date-time
             * @description Timestamp when the note was created.
             */
            created_at?: string;
        };
        /**
         * AdminNoteLevel
         * @description Severity level for admin notes on a domain classification.
         * @enum {string}
         */
        AdminNoteLevel: "info" | "warning" | "danger";
        /**
         * ExtensionReportRequest
         * @description Request body for POST /extensions/report.
         */
        ExtensionReportRequest: {
            /**
             * Url
             * @description The URL being reported
             */
            url: string;
            /**
             * Content
             * @description Why the user believes this site is a threat
             */
            content: string;
        };
        /**
         * ExtensionReportResponse
         * @description Response body for a submitted report.
         */
        ExtensionReportResponse: {
            /**
             * Id
             * Format: uuid
             * @description The created post ID
             */
            id: string;
            /**
             * Domain
             * @description Normalized registered domain
             */
            domain: string;
            /** @description Initial moderation status */
            status: components["schemas"]["PostStatus"];
        };
        /**
         * PostStatus
         * @description Status of a post in the AI moderation workflow.
         *
         *     Posts follow a "guilty until proven innocent" model where they start
         *     as PENDING and must be approved before becoming visible.
         * @enum {string}
         */
        PostStatus: "pending" | "approved" | "needs_review" | "rejected" | "removed";
        /**
         * ScanRequest
         * @description Request body for POST /extensions/scan.
         */
        ScanRequest: {
            /**
             * Url
             * @description URL being scanned
             */
            url: string;
            /**
             * Screenshot Base64
             * @description Base64-encoded JPEG screenshot of the page
             */
            screenshot_base64: string;
            /**
             * Html
             * @description HTML content of the page
             */
            html: string;
        };
        /**
         * SubscriptionJobInitResponse
         * @description Response for subscription job creation.
         */
        SubscriptionJobInitResponse: {
            /**
             * Job Id
             * @description Subscription job ID for polling
             */
            job_id: string;
            /**
             * Status Url
             * @description URL to poll for job status
             */
            status_url: string;
        };
        /** SubscriptionJobStatusResponse[ExtensionScanResult] */
        SubscriptionJobStatusResponse_ExtensionScanResult_: {
            status: components["schemas"]["SubscriptionJobStatus"];
            result?: components["schemas"]["ExtensionScanResult"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * SubscriptionJobStatus
         * @description Status values for subscription jobs.
         * @enum {string}
         */
        SubscriptionJobStatus: "processing" | "complete" | "failed";
        /**
         * ExtensionScanResult
         * @description API response model for extension scan results.
         *
         *     Same shape as ``ExtensionReport`` but excludes internal fields like
         *     ``audit_trail`` that should not be exposed to extension users.
         *     Extra fields in the stored dict are silently ignored by Pydantic
         *     validation so this naturally strips ``audit_trail``.
         */
        ExtensionScanResult: {
            /** Request Url */
            request_url: string;
            safety_level: components["schemas"]["SafetyLevel"];
            /** Summary */
            summary: string;
            /** Risks */
            risks?: string[];
            /** Tips */
            tips?: string[];
            /** Brand Warning */
            brand_warning?: string | null;
            /** Domain Registered Date */
            domain_registered_date?: string | null;
        };
        /**
         * SafetyLevel
         * @description User-facing safety classification.
         * @enum {string}
         */
        SafetyLevel: "safe" | "caution" | "danger";
        /**
         * SubscriptionResponse
         * @description Response for GET /extensions/subscription.
         */
        SubscriptionResponse: {
            /** Name */
            name?: string | null;
            /** Daily Scan Limit */
            daily_scan_limit?: number | null;
            /** Is Active */
            is_active: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_current_user_extensions_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Urlert-Install-ID"?: string | null;
                "X-Urlert-Extension-ID"?: string | null;
                "X-Urlert-Version"?: string | null;
                "X-Urlert-Guard-Source"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_domain_classification_extensions_domain_classification__domain__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Urlert-Install-ID"?: string | null;
                "X-Urlert-Extension-ID"?: string | null;
                "X-Urlert-Version"?: string | null;
                "X-Urlert-Guard-Source"?: string | null;
                Authorization?: string | null;
            };
            path: {
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainClassificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_report_extensions_report_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Urlert-Install-ID"?: string | null;
                "X-Urlert-Extension-ID"?: string | null;
                "X-Urlert-Version"?: string | null;
                "X-Urlert-Guard-Source"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtensionReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtensionReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    initiate_scan_extensions_scan_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Urlert-Install-ID"?: string | null;
                "X-Urlert-Extension-ID"?: string | null;
                "X-Urlert-Version"?: string | null;
                "X-Urlert-Guard-Source"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionJobInitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_status_extensions_scan__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Urlert-Install-ID"?: string | null;
                "X-Urlert-Extension-ID"?: string | null;
                "X-Urlert-Version"?: string | null;
                "X-Urlert-Guard-Source"?: string | null;
                Authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionJobStatusResponse_ExtensionScanResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subscription_extensions_subscription_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Urlert-Install-ID"?: string | null;
                "X-Urlert-Extension-ID"?: string | null;
                "X-Urlert-Version"?: string | null;
                "X-Urlert-Guard-Source"?: string | null;
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
